### ISSUE TITLE
[Tracking] Make our Actions workflows more secure

### ISSUE THREAD

**Issue by zeke** [github/docs#128]
We want our use of GitHub Actions to be a secure as possible. This is a tracking issue for steps we can take to make them more secure. See https://github.com/github/security/issues/3907

- [x] Create a test to lint workflows for correctness and consistency https://github.com/github/help-docs/pull/13181
- [x] https://github.com/github/docs/pull/555 Use SHAs instead of version numbers for all `uses` values (see https://github.com/github/security/issues/3907#issuecomment-619103152)
- [x] Create an AllowList of known/trusted Action authors https://github.com/github/docs-internal/pull/15850

cc @github/content-platform-engineering

**Comment by chiedo** [comment]
Opened a PR to move all versions to shas! https://github.com/github/docs/pull/555

**Comment by chiedo** [comment]
Handled the shas! Will leave the following for someone else

> Create a test to lint workflows for correctness and consistency
