### ISSUE TITLE
Im not leaving 

### ISSUE THREAD

**Issue by Wookie9809** [github/docs#19045]
### Code of Conduct

- [ ] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### Pre-requisites

- [ ] My application to the GitHub Technology Partner Program is approved.

### Tasks

- [ ] MUST follow our [general contributing guidelines](CONTRIBUTING.md) for voice and markup format.
- [ ] MUST emphasize how the third-party product works with GitHub.
- [ ] MUST be written in Markdown format, using [one of the templates provided](contributing/github-partners/README.md#templates).
- [ ] MUST include the name and URL of the GitHub technology partner responsible for maintenance of the documentation being contributed. This should be added via the `contributor.name` and `contributor.URL` properties in the template's YAML frontmatter.
- [ ] MUST be proposed via a pull request to this repo following [the GitHub Flow](https://guides.github.com/introduction/flow/).
- [ ] MUST be located in the root of [the `content` folder](content). Your filename MUST match the GitHub technology partner name, and use the `.md` file extension.

### Pull Request

- [ ] MUST reference this issue, e.g. via `closes [this issue number]`.
- [ ] MUST pass the automated CI checks.
- [ ] MUST include links to supporting material demonstrating the functionality being documented (this can be a link to a public GitHub repo, _or_ a video / screencast walkthrough).

**Comment by Wookie9809** [comment]
You no me better than that hommie[](url)

**Comment by Wookie9809** [comment]
1. [ ] 

> ### 

# @- > [`**``**`](url)

**Comment by orekihoutaro** [comment]
LGMT!
Code of conduct should be updated...

**Comment by pallarajasekhar** [comment]
-_-
