### ISSUE TITLE
PullApprove partner-owned documentation

### ISSUE THREAD

**Issue by davegaeddert** [github/docs#25734]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### Pre-requisites

- [X] My application to the GitHub Technology Partner Program is approved.

### Tasks

- [ ] MUST follow our [general contributing guidelines](CONTRIBUTING.md) for voice and markup format.
- [ ] MUST emphasize how the third-party product works with GitHub.
- [ ] MUST be written in Markdown format, using [one of the templates provided](contributing/github-partners/README.md#templates).
- [ ] MUST include the name and URL of the GitHub technology partner responsible for maintenance of the documentation being contributed. This should be added via the `contributor.name` and `contributor.URL` properties in the template's YAML frontmatter.
- [ ] MUST be proposed via a pull request to this repo following [the GitHub Flow](https://guides.github.com/introduction/flow/).
- [ ] MUST be located in the root of [the `content` folder](content). Your filename MUST match the GitHub technology partner name, and use the `.md` file extension.

### Pull Request

- [ ] MUST reference this issue, e.g. via `closes [this issue number]`.
- [ ] MUST pass the automated CI checks.
- [ ] MUST include links to supporting material demonstrating the functionality being documented (this can be a link to a public GitHub repo, _or_ a video / screencast walkthrough).

**Comment by davegaeddert** [comment]
Hey @github/partner-engineering, I'm curious if partner-owned documentation is still a thing? I see the issue template still exists but I remember this from quite a while ago, and am not actually aware of any current examples of partner-owned docs or other references to it. Let me know! I may be interested in it for PullApprove if possible (https://www.pullapprove.com/).

**Comment by davegaeddert** [comment]
Maybe @github/partner-engineering no longer exists... @cmwilson21 is this something you could help with?

**Comment by cmwilson21** [comment]
@davegaeddert Thanks for reaching out. I'm unsure about this one, so I'm looking into it internally. I'll reach out when/if I hear anything. Leaving this open and labeled `triage` for now for tracking purposes.

**Comment by Mohammedfallatah** [comment]
.

**Comment by mattlovestech** [comment]
@davegaeddert Can you share more about what type of partner docs you want to collaborate on? Typically our team has updated the docs, when relevant, to include partner info.

**Comment by davegaeddert** [comment]
Hey @mattlovestech! It may be a question of what (if anything) is possible. My memory from before is that there was a push/offer for the Technology Partners to co-publish "partner-owned documentation" in the GitHub docs. My guess is that the idea sort of fizzled out but this issue template was never deleted (and should be?). Obviously I would be happy to see PullApprove worked into the docs somewhere, but I don't have a concrete suggestion for where to do that at the moment. I'll close this issue but let me know if you have any thoughts. Thanks!
