### ISSUE TITLE
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

### ISSUE THREAD

**Issue by zvailanu98** [github/docs#26845]
Thanks for opening this pull request! A GitHub docs team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/github/docs/blob/main/CONTRIBUTING.md).

_Originally posted by @welcome[bot] in https://github.com/github/docs/issues/26806#issuecomment-1637107198_
            
```[tasklist]
### Tasks
- [x] Revert "remove z-index of sup"
- [ ] https://github.com/github/docs/pull/26842
- [ ] https://github.com/github/docs/pull/20732
- [ ] https://github.com/github/docs/pull/26699
- [ ] https://github.com/github/docs/pull/26837
- [ ] https://github.com/github/docs/pull/20069
- [ ] https://github.com/github/docs/issues/8926
- [ ] https://github.com/github/docs/pull/26202
- [ ] https://github.com/github/docs/issues/26844
- [ ] https://github.com/github/docs/pull/26838
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/20732
- [ ] https://github.com/github/docs/pull/26837
- [ ] https://github.com/github/docs/issues/26844
- [ ] https://github.com/github/docs/issues/8926
- [ ] https://github.com/github/docs/pull/26699
- [ ] https://github.com/github/docs/pull/26835
- [ ] https://github.com/github/docs/pull/26202
- [ ] https://github.com/github/docs/pull/26842
- [x] )
- [x] Automatic
- [ ] https://github.com/github/docs/pull/26833
- [ ] https://github.com/github/docs/pull/26698
- [ ] https://github.com/github/docs/pull/26832
```
