### ISSUE TITLE
Improve github docs

### ISSUE THREAD

**Issue by ReyBan82** [github/docs#26961]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All

### What changes are you suggesting?

All

### Additional information

Ownership
```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/20819
- [ ] https://github.com/github/docs/pull/25720
- [ ] https://github.com/github/docs/pull/26959
```

**Comment by cmwilson21** [comment]
This seems to have been opened accidentally, I am going to close it now :yellow_heart: 

Take a look at the [contributing.md](https://github.com/github/docs/blob/main/CONTRIBUTING.md/) to learn how to contribute in this repo. You can open a [discussion](https://github.com/github/docs/discussions) if you have any questions or check out issues with the [help wanted](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label. :sparkles:
