### ISSUE TITLE
Improve existing content

### ISSUE THREAD

**Issue by BET3S** [github/docs#28162]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

Please link to the article I'd like to see updated.

### What part(s) of the article would you like to see updated?

• Give as much detail as you can to help us understand the change you want to see.
• Why should the docs be changed? • • What use cases does it support?
• What is the expected outcome or behavior?

```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/28161
- [ ] https://github.com/github/docs/pull/28159
- [ ] https://github.com/github/docs/pull/28140
- [ ] https://github.com/github/docs/issues/28156
- [ ] https://github.com/github/docs/pull/28155
```

**Comment by BET3S** [comment]
Done
