### ISSUE TITLE
partner owned

### ISSUE THREAD

**Issue by Dani-beef** [github/docs#28759]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### Pre-requisites

- [X] My application to the GitHub Technology Partner Program is approved.

### Tasks

- [X] MUST follow our [general contributing guidelines](https://docs.github.com/en/contributing) for voice and markup format.
- [X] MUST emphasize how the third-party product works with GitHub.
- [X] MUST be written in Markdown format, using [one of the templates provided](contributing/github-partners/README.md#templates).
- [X] MUST include the name and URL of the GitHub technology partner responsible for maintenance of the documentation being contributed. This should be added via the `contributor.name` and `contributor.URL` properties in the template's YAML frontmatter.
- [X] MUST be proposed via a pull request to this repo following [the GitHub Flow](https://guides.github.com/introduction/flow/).
- [X] MUST be located in the root of [the `content` folder](content). Your filename MUST match the GitHub technology partner name, and use the `.md` file extension.

### Pull Request

- [X] MUST reference this issue, e.g. via `closes [this issue number]`.
- [X] MUST pass the automated CI checks.
- [X] MUST include links to supporting material demonstrating the functionality being documented (this can be a link to a public GitHub repo, _or_ a video / screencast walkthrough).

**Comment by PurpleMaster1** [comment]
> ### 行為準則 > * [x] 我已閱讀並同意GitHub Docs專案[行為準則](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md) > > ### 先決條件 > * [x] 我向GitHub技術合作夥伴計劃的申請已獲批准。 > > ### 任務 > * [x] 必須遵循我們關於語音和標記格式[的一般貢獻指南](https://docs.github.com/en/contributing)。 > * [x] 必須強調第三方產品如何與GitHub配合使用。 > * [x] 必須使用[提供的模板之一](contributing/github-partners/README.md#templates)以Markdown格式。編寫 > * [x] 必須包括負責維護所貢獻文件的GitHub技術合作夥伴的名稱和URL。 這應該透過模板的YAML前大事項中的`contributor.name`和`contributor.URL`屬性新增。 > * [x] 必須[按照GitHub流程](https://guides.github.com/introduction/flow/)透過拉取請求向此回購提出協議。 > * [x] 必須位於[`content`資料夾](content)的根目錄中。 您的檔名必須與GitHub技術合作夥伴名稱匹配，並使用`.md`副檔名。 > > ### 拉取請求 > * [x] 必須參考此問題，例如透過`關閉[此問題號]`。 > * [x] 必須透過自動CI檢查。 > * [x] 必須包含演示正在記錄的功能的支援材料的連結（這可以是公共GitHub回購網的連結，_也可以_是影片/截屏演）。  ![ 上傳IMG_2135.png...]()

違反基本原則涉及侵犯個人隱私所以請更新內容否則將提出法律追訴權！
ㄨ
