### ISSUE TITLE
docs.github.com

### ISSUE THREAD

**Issue by kaaid** [github/docs#29667]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

docs.github.com

### What part(s) of the article would you like to see updated?

 #``

```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/29666
- [ ] https://github.com/github/docs/pull/29663
- [ ] https://github.com/github/docs/pull/29662
- [ ] https://github.com/github/docs/pull/29665
- [ ] https://github.com/github/docs/pull/29661
- [ ] https://github.com/github/docs/pull/29664
- [ ] https://github.com/github/docs/pull/29659
- [ ] https://github.com/github/docs/pull/29658
- [ ] https://github.com/github/docs/pull/29656
- [ ] https://github.com/github/docs/pull/29412
- [ ] https://github.com/github/docs/issues/29660
- [ ] https://github.com/github/docs/issues/29566
```
