### ISSUE TITLE
👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions:

### ISSUE THREAD

**Issue by cokyman** [github/docs#35584]
👋 Hey there spelunker. It looks like you've modified some files that we can't accept as contributions:
 - .devcontainer/devcontainer.json
 - .github/workflows/node.js.yml
 - .github/workflows/notify-about-deployment.yml

You'll need to revert all of the files you changed that match that list using [GitHub Desktop](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/reverting-a-commit-in-github-desktop) or `git checkout origin/main <file name>`. Once you get those files reverted, we can continue with the review process. :octocat:

The complete list of files we can't accept are:
 - .devcontainer/**
 - .github/**
 - data/reusables/rai/**
 - Dockerfile*
 - src/**
 - package*.json
 - content/actions/deployment/security-hardening-your-deployments/**

We also can't accept contributions to files in the content directory with frontmatter `type: rai`.

_Originally posted by @github-actions[bot] in https://github.com/github/docs/issues/35580#issuecomment-2525968532_
            
```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/pull/35580
- [ ] https://github.com/github/docs/pull/35581
- [ ] https://github.com/github/docs/pull/35448
- [ ] https://github.com/github/docs/issues/31611
- [ ] https://github.com/github/docs/pull/35575
- [ ] https://github.com/github/docs/pull/35468
- [ ] https://github.com/github/docs/issues/35577
- [ ] https://github.com/github/docs/pull/35576
- [ ] https://github.com/github/docs/issues/35573
- [ ] https://github.com/github/docs/issues/35571
- [ ] https://github.com/github/docs/pull/35414
- [ ] https://github.com/github/docs/pull/35570
```

**Comment by cokyman** [comment]
gh pr checkout 35580
