### ISSUE TITLE
سيتم التعامل مع تحديث التبعية هذا داخليا من قبل فريقنا الهندسي.

### ISSUE THREAD

**Issue by shnnan1** [github/docs#35712]
This dependency update will be handled internally by our engineering team.

_Originally posted by @github-actions[bot] in https://github.com/github/docs/issues/33195#issuecomment-2134412877_
            
```[tasklist]
### Tasks
- [ ] https://github.com/github/docs/issues/35710
- [ ] https://github.com/github/docs/pull/35595
- [ ] https://github.com/github/docs/pull/35711
```

**Comment by shnnan1** [comment]
G
